In [49]:
import pandas as pd
import numpy as np

In [55]:
# Concatenate all the dataframes of DSCOVR
dscovr_data = pd.read_csv("dscovrNEW/dsc_fc_summed_spectra_2016_v01.csv")

for path in range(2017, 2024):
    new_dscovr = pd.read_csv("dscovrNEW/dsc_fc_summed_spectra_"+ str(path)+"_v01.csv")
    dscovr_data = pd.concat([dscovr_data, new_dscovr], ignore_index=True)

print(dscovr_data.shape)

(54432, 57)

In [51]:
# Concatenate all the dataframes of the validation data
valid_data = pd.read_csv("valid/omni2016.csv")

for path in range(2017, 2024):
    new_valid = pd.read_csv("valid/omni"+ str(path)+".csv")
    valid_data = pd.concat([valid_data, new_valid], ignore_index=True)

valid_data.rename(columns = {'YEAR': 'year', 'DAY': 'day', 'HOUR': 'hour'}, inplace = True)

In [53]:
# Merging with the validation data
dscovr_data.merge(valid_data, on=['year', 'day', 'hour'], how='left', indicator=True)

,year,day,hour,minute,bx,by,bz,row1,row2,row3,...,"SW Proton Density, N/cm^3","SW Plasma Speed, km/s",SW Plasma flow long. angle,SW Plasma flow lat. angle,Flow pressure,Kp index,Dst-index,AL-index,AU-index,_merge
0,2016,1,0,60,5.733193,-2.296756,-13.282797,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,2016,1,1,60,4.668200,-1.917471,-12.976817,NaN,NaN,NaN,...,0.8,451.0,-2.8,1.3,0.33,60.0,-114.0,-512.0,62.0,both
2,2016,1,2,60,2.898088,0.470586,-13.237948,NaN,NaN,NaN,...,1.1,450.0,-3.2,1.4,0.45,60.0,-102.0,-564.0,224.0,both
3,2016,1,3,60,3.107440,0.077172,-12.819543,NaN,NaN,NaN,...,1.7,434.0,-7.6,1.1,0.64,53.0,-98.0,-555.0,156.0,both
4,2016,1,4,60,3.387239,-2.777962,-11.102431,NaN,NaN,NaN,...,0.9,430.0,-6.3,0.3,0.33,53.0,-96.0,-672.0,237.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54427,2023,122,19,60,3.625422,3.330697,-1.425394,0.233362,0.231726,1.842298,...,1.7,479.0,5.4,-4.1,0.70,17.0,-23.0,99999.0,99999.0,both
54428,2023,122,20,60,3.129382,3.551040,-1.273540,0.597925,0.231726,7.548884,...,1.9,475.0,5.3,-4.9,0.77,17.0,-21.0,99999.0,99999.0,both
54429,2023,122,21,60,4.297767,3.180053,-1.004981,1.045634,0.231726,7.808236,...,2.0,474.0,4.5,-3.4,0.80,7.0,-19.0,99999.0,99999.0,both
54430,2023,122,22,60,4.677120,3.084730,0.446979,0.530784,0.231726,13.019587,...,1.8,468.0,4.9,-2.6,0.70,7.0,-17.0,99999.0,99999.0,both
54431,2023,122,23,60,3.723668,3.607139,0.398778,0.703021,0.231726,15.057400,...,1.4,459.0,3.9,-1.9,0.53,7.0,-13.0,99999.0,99999.0,both